name: flutter_idcard_reader
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  thai_idcard_reader_flutter:
    path: pkgs/thai_idcard_reader_flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  font_awesome_flutter: ^10.2.1
  fluentui_system_icons: ^1.1.188

  zoom_widget: ^2.0.0
  flip_card: ^0.6.0
  lottie: ^1.4.3
  flutter_native_splash: ^2.2.12

  intl: ^0.18.0
  shared_preferences: ^2.0.15
  page_transition: ^2.0.9
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  drop_shadow: ^0.0.2+1
  image_picker: ^0.8.6
  carousel_slider: ^4.2.0
  google_maps_flutter: ^2.2.5

  dio: ^5.1.2
  json_annotation: ^4.8.1
  retrofit: ^4.0.1
  path_provider: ^2.0.15
  path: ^1.8.2
  permission_handler: ^9.2.0
  sembast: ^3.2.0
  rxdart: ^0.27.3
  riverpod: ^1.0.3
  flutter_riverpod: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.1
  build_runner: ">=2.3.0 <4.0.0"
  json_serializable: ^6.1.5

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
